1704619676597	Sync.LogManager	DEBUG	Flushing file log
1704619676599	Sync.LogManager	DEBUG	Log cleanup threshold time: 1703755676599
1704619676604	Sync.LogManager	DEBUG	Done deleting files.
1704619676641	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1704619676641	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1704619676642	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1704619688306	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1704619688394	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1704619688395	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1704619688400	Sync.Service	DEBUG	User-Agent: Firefox/121.0 (Intel Mac OS X 10.15) FxSync/1.123.0.20231211174248.desktop
1704619688400	Sync.Service	INFO	Starting sync at 2024-01-07 09:28:08 in browser session _omFv-UkiPfU
1704619688400	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1704619688404	Sync.Status	INFO	Resetting Status.
1704619688404	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1704619688405	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1704619688444	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/197306892/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704619688444	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1704619688444	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1704619688444	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1704619688444	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1704619688445	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
